// This code is auto-generated by the VM translator
// Name: VMtranslator
// Version: 1.0.0.0
// Date: 20/09/2026 18:16:18

// Initialize stack pointer to 256
    @256
    D=A
    @SP
    M=D
// End of initialization
// File: BasicTest.vm
    @10            // Load constant '10' value into A
    D=A                 // Store '10' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '10' onto the stack
    @SP
    M=M+1               // SP++;
    @LCL
    D=M
    @0
    D=D+A

    @R13
    M=D                 // Store the effective address in R13

    @SP
    AM=M-1              // SP--; A=SP
    D=M                 // Store the top of the stack in D

    @R13
    A=M
    M=D
    @21            // Load constant '21' value into A
    D=A                 // Store '21' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '21' onto the stack
    @SP
    M=M+1               // SP++;
    @22            // Load constant '22' value into A
    D=A                 // Store '22' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '22' onto the stack
    @SP
    M=M+1               // SP++;
    @ARG
    D=M
    @2
    D=D+A

    @R13
    M=D                 // Store the effective address in R13

    @SP
    AM=M-1              // SP--; A=SP
    D=M                 // Store the top of the stack in D

    @R13
    A=M
    M=D
    @ARG
    D=M
    @1
    D=D+A

    @R13
    M=D                 // Store the effective address in R13

    @SP
    AM=M-1              // SP--; A=SP
    D=M                 // Store the top of the stack in D

    @R13
    A=M
    M=D
    @36            // Load constant '36' value into A
    D=A                 // Store '36' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '36' onto the stack
    @SP
    M=M+1               // SP++;
    @THIS
    D=M
    @6
    D=D+A

    @R13
    M=D                 // Store the effective address in R13

    @SP
    AM=M-1              // SP--; A=SP
    D=M                 // Store the top of the stack in D

    @R13
    A=M
    M=D
    @42            // Load constant '42' value into A
    D=A                 // Store '42' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '42' onto the stack
    @SP
    M=M+1               // SP++;
    @45            // Load constant '45' value into A
    D=A                 // Store '45' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '45' onto the stack
    @SP
    M=M+1               // SP++;
    @THAT
    D=M
    @5
    D=D+A

    @R13
    M=D                 // Store the effective address in R13

    @SP
    AM=M-1              // SP--; A=SP
    D=M                 // Store the top of the stack in D

    @R13
    A=M
    M=D
    @THAT
    D=M
    @2
    D=D+A

    @R13
    M=D                 // Store the effective address in R13

    @SP
    AM=M-1              // SP--; A=SP
    D=M                 // Store the top of the stack in D

    @R13
    A=M
    M=D
    @510            // Load constant '510' value into A
    D=A                 // Store '510' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '510' onto the stack
    @SP
    M=M+1               // SP++;
    @5
    D=M
    @6
    D=D+A

    @R13
    M=D                 // Store the effective address in R13

    @SP
    AM=M-1              // SP--; A=SP
    D=M                 // Store the top of the stack in D

    @R13
    A=M
    M=D
    @LCL           // Load base address of segment 'LCL' into A, e.g., LCL for local, ARG for argument
    D=M                  // Store the base address of segment 'LCL' in D
    @0             // Load the index '0' into A
    D=D+A                // Compute the effective address of segment 'LCL' at index '0'
    @SP
    M=D                  // Push the effective address onto the stack
    @THAT           // Load base address of segment 'THAT' into A, e.g., LCL for local, ARG for argument
    D=M                  // Store the base address of segment 'THAT' in D
    @5             // Load the index '5' into A
    D=D+A                // Compute the effective address of segment 'THAT' at index '5'
    @SP
    M=D                  // Push the effective address onto the stack
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M+D
    @ARG           // Load base address of segment 'ARG' into A, e.g., LCL for local, ARG for argument
    D=M                  // Store the base address of segment 'ARG' in D
    @1             // Load the index '1' into A
    D=D+A                // Compute the effective address of segment 'ARG' at index '1'
    @SP
    M=D                  // Push the effective address onto the stack
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M-D
    @THIS           // Load base address of segment 'THIS' into A, e.g., LCL for local, ARG for argument
    D=M                  // Store the base address of segment 'THIS' in D
    @6             // Load the index '6' into A
    D=D+A                // Compute the effective address of segment 'THIS' at index '6'
    @SP
    M=D                  // Push the effective address onto the stack
    @THIS           // Load base address of segment 'THIS' into A, e.g., LCL for local, ARG for argument
    D=M                  // Store the base address of segment 'THIS' in D
    @6             // Load the index '6' into A
    D=D+A                // Compute the effective address of segment 'THIS' at index '6'
    @SP
    M=D                  // Push the effective address onto the stack
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M+D
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M-D
    @5           // Load base address of segment '5' into A, e.g., LCL for local, ARG for argument
    D=M                  // Store the base address of segment '5' in D
    @6             // Load the index '6' into A
    D=D+A                // Compute the effective address of segment '5' at index '6'
    @SP
    M=D                  // Push the effective address onto the stack
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M+D

    @END
    0;JMP
(END)
    @END
    0;JMP      // Infinite loop
// End of translation

