// This code is auto-generated by the VM translator
// Name: VMtranslator
// Version: 1.0.0.0
// Date: 20/09/2026 16:25:35

// Initialize stack pointer to 256
    @256
    D=A
    @SP
    M=D
// End of initialization
// File: StackTest.vm
    @17            // Load constant '17' value into A
    D=A                 // Store '17' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '17' onto the stack
    @SP
    M=M+1               // SP++;
    @17            // Load constant '17' value into A
    D=A                 // Store '17' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '17' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    D=M-D
    @EQ_TRUE_0
    D;JEQ

    @SP
    A=M-1
    M=0                 // False
    @EQ_END_0
    0;JMP

(EQ_TRUE_0)
    @SP
    A=M-1
    M=-1                // True

(EQ_END_0)
    @17            // Load constant '17' value into A
    D=A                 // Store '17' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '17' onto the stack
    @SP
    M=M+1               // SP++;
    @16            // Load constant '16' value into A
    D=A                 // Store '16' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '16' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    D=M-D
    @EQ_TRUE_1
    D;JEQ

    @SP
    A=M-1
    M=0                 // False
    @EQ_END_1
    0;JMP

(EQ_TRUE_1)
    @SP
    A=M-1
    M=-1                // True

(EQ_END_1)
    @16            // Load constant '16' value into A
    D=A                 // Store '16' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '16' onto the stack
    @SP
    M=M+1               // SP++;
    @17            // Load constant '17' value into A
    D=A                 // Store '17' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '17' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    D=M-D
    @EQ_TRUE_2
    D;JEQ

    @SP
    A=M-1
    M=0                 // False
    @EQ_END_2
    0;JMP

(EQ_TRUE_2)
    @SP
    A=M-1
    M=-1                // True

(EQ_END_2)
    @892            // Load constant '892' value into A
    D=A                 // Store '892' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '892' onto the stack
    @SP
    M=M+1               // SP++;
    @891            // Load constant '891' value into A
    D=A                 // Store '891' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '891' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    D=M-D
    @LT_TRUE_3
    D;JLT

    @SP
    A=M-1
    M=0                 // False
    @LT_END_3
    0;JMP

(LT_TRUE_3)
    @SP
    A=M-1
    M=-1                // True

(LT_END_3)
    @891            // Load constant '891' value into A
    D=A                 // Store '891' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '891' onto the stack
    @SP
    M=M+1               // SP++;
    @892            // Load constant '892' value into A
    D=A                 // Store '892' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '892' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    D=M-D
    @LT_TRUE_4
    D;JLT

    @SP
    A=M-1
    M=0                 // False
    @LT_END_4
    0;JMP

(LT_TRUE_4)
    @SP
    A=M-1
    M=-1                // True

(LT_END_4)
    @891            // Load constant '891' value into A
    D=A                 // Store '891' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '891' onto the stack
    @SP
    M=M+1               // SP++;
    @891            // Load constant '891' value into A
    D=A                 // Store '891' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '891' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    D=M-D
    @LT_TRUE_5
    D;JLT

    @SP
    A=M-1
    M=0                 // False
    @LT_END_5
    0;JMP

(LT_TRUE_5)
    @SP
    A=M-1
    M=-1                // True

(LT_END_5)
    @32767            // Load constant '32767' value into A
    D=A                 // Store '32767' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '32767' onto the stack
    @SP
    M=M+1               // SP++;
    @32766            // Load constant '32766' value into A
    D=A                 // Store '32766' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '32766' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    D=M-D
    @GT_TRUE_6
    D;JGT

    @SP
    A=M-1
    M=0                 // False
    @GT_END_6
    0;JMP

(GT_TRUE_6)
    @SP
    A=M-1
    M=-1            // True

(GT_END_6)
    @32766            // Load constant '32766' value into A
    D=A                 // Store '32766' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '32766' onto the stack
    @SP
    M=M+1               // SP++;
    @32767            // Load constant '32767' value into A
    D=A                 // Store '32767' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '32767' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    D=M-D
    @GT_TRUE_7
    D;JGT

    @SP
    A=M-1
    M=0                 // False
    @GT_END_7
    0;JMP

(GT_TRUE_7)
    @SP
    A=M-1
    M=-1            // True

(GT_END_7)
    @32766            // Load constant '32766' value into A
    D=A                 // Store '32766' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '32766' onto the stack
    @SP
    M=M+1               // SP++;
    @32766            // Load constant '32766' value into A
    D=A                 // Store '32766' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '32766' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    D=M-D
    @GT_TRUE_8
    D;JGT

    @SP
    A=M-1
    M=0                 // False
    @GT_END_8
    0;JMP

(GT_TRUE_8)
    @SP
    A=M-1
    M=-1            // True

(GT_END_8)
    @57            // Load constant '57' value into A
    D=A                 // Store '57' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '57' onto the stack
    @SP
    M=M+1               // SP++;
    @31            // Load constant '31' value into A
    D=A                 // Store '31' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '31' onto the stack
    @SP
    M=M+1               // SP++;
    @53            // Load constant '53' value into A
    D=A                 // Store '53' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '53' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M+D
    @112            // Load constant '112' value into A
    D=A                 // Store '112' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '112' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M-D
    @SP
    A=M-1
    M=-M
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M&D
    @82            // Load constant '82' value into A
    D=A                 // Store '82' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '82' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M|D
    @SP
    A=M-1
    M=!M

    @END
    0;JMP
(END)
    @END
    0;JMP      // Infinite loop
// End of translation

