// This code is auto-generated by the VM translator
// Name: VMtranslator
// Version: 1.0.0.0
// Date: 20/09/2026 16:25:39

// Initialize stack pointer to 256
    @256
    D=A
    @SP
    M=D
// End of initialization
// File: SimpleAdd.vm
    @7            // Load constant '7' value into A
    D=A                 // Store '7' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '7' onto the stack
    @SP
    M=M+1               // SP++;
    @8            // Load constant '8' value into A
    D=A                 // Store '8' in D
    @SP
    A=M                 // Load the top of the stack into A
    M=D                 // Push '8' onto the stack
    @SP
    M=M+1               // SP++;
    @SP
    AM=M-1
    D=M
    A=A-1
    M=M+D

    @END
    0;JMP
(END)
    @END
    0;JMP      // Infinite loop
// End of translation

